matrix:
  include:
  - os: linux
    dist: xenial # use Ubuntu 16.04 LTS will be the minimum required version for the AppImage
    language: python
    python: "3.6" # pin for Linux builds (on macos, the multibuild python is used instead)
  - os: osx
    language: generic
env:
  - MB_PYTHON_VERSION=3.6
script:
  - source ./.travis/install.sh
deploy:
  provider: releases
  draft: true
  api_key:
    secure: N19tf9SJmo3KluUL3DjGMxTTGaa9/qu6UNxqPtOyRu/StSzU1yeh1D8oZr+qYl6tWeqogvSWKlDw78Dp1c4Ro0IQB7ebgxT4YJGF6DeuCo1gvi1uE84Xh+Hl+Y4urS52F3ABSAHejhYhJW7XxsrA3MCiz56S7OEsuDp1u4fG8LM=
  file: $ARTIFACT_FILENAME
  skip_cleanup: true
  on:
    repo: tlecomte/friture
