environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
  matrix:
    - PYTHON: "C:/Python35"
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - ps: "ls C:/Python35/"
  - ps: "ls C:/Python35/Scripts/"
  - "%PYTHON%/python --version"
  - "%PYTHON%/Scripts/pip --version"
  # Set the relevant python and pip location to the path
  - cmd: set PATH=%PYTHON%;%PYTHON%\scripts;%PATH%
  - cmd: ECHO Path - %PATH%
install:
  # the real work happens there
  - ps: ./winbuild.ps1
build: false
artifacts:
  - path: installer/friture-*.exe
    name: friture-setup
  - path: build/friture/xref-friture.html
    name: xref-friture
deploy:
  provider: GitHub
  auth_token:
    secure: G+gWuedV/W/4omkXG1VVmu0AP8+E5jehFo8Hte5fZxeA1XKW29bnbxk0GJUOtnVz
  artifact: friture-setup
  draft: true
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
